package(default_visibility = ["//visibility:public"])

py_library(
    name = "pub_sub_manager",
    srcs = ["pub_sub_manager.py"],
    deps = [
        "//lib/py/net:util",
        "//main/dir_server/view:server_view",
    ],
)
