package(default_visibility = ["//visibility:public"])

py_library(
    name = "mysql_manager",
    srcs = ["mysql_manager.py"],
)

py_library(
    name = "redis_manager",
    srcs = ["redis_manager.py"],
)
